# Generated by Django 3.1.1 on 2020-09-16 17:35

import contributions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video_link', models.URLField(help_text='Lenke til Vimeo eller YouTube video.')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(default=contributions.models.get_random_token, max_length=10)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.contribution')),
            ],
        ),
    ]
