# Generated by Django 3.1.1 on 2020-09-17 20:36

import contributions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contact_email',
            field=models.EmailField(default='thorvla.2@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='confirmation_token',
            field=models.CharField(default=contributions.models.get_random_token, max_length=20, unique=True),
        ),
    ]
