# Generated by Django 3.1.1 on 2020-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_auto_20200921_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvote',
            name='username',
            field=models.CharField(db_index=True, max_length=20, verbose_name='NTNU-brukernavn'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='NTNU-brukernavn'),
        ),
    ]
