# Generated by Django 3.1.1 on 2020-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_auto_20200917_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
